export type EnvKey =
  | "VITE_MAGIC_PUBLIC_KEY"
  | "VITE_MAGIC_SECRET_KEY"
  | "VITE_CHAIN_ID"
  | "VITE_NETWORK"
  | "VITE_RPC_URL"
  | "VITE_CONTRACT_ADDRESS"
  | "VITE_INFURA_SECRET_KEY"
  | "REACT_APP_SUPABASE_URL"
  | "REACT_APP_SUPABASE_ANON_KEY";
